### ISSUE TITLE
Better labels for precipitation

### ISSUE THREAD

**Issue by mhkeller** [vsergeev/briefsky#12]
The copy says `Precipitation` for both the probability and the amount. It would be clearer if these were "Precipitation" for probability and "Amount" for the amount. It would be worth figuring out better, more readable copy for when these values are zero such as "No rain"

Here's a screenshot showing the duplicate fields.

![IMG_2994](https://user-images.githubusercontent.com/498744/232970486-a17773ce-ce64-40a6-a97b-42403a05e1fc.jpg)

**Comment by vsergeev** [comment]
I'm definitely open to suggestions on this one. The main reason there are two `Precipitation` labels is because some weather providers only provide one of the two (chance or amount), while `Precipitation Chance` and `Precipitation Amount` seemed pretty long labels for those fields. (OpenMeteo has both.)
