### ISSUE TITLE
Example weather provider warning even after provider added

### ISSUE THREAD

**Issue by mhkeller** [vsergeev/briefsky#6]
Great app! I added weather credentials but I'm still getting the box at the top saying that this is an example weather provider. I refreshed a couple of times but it remains. Opening up settings and my credentials are there.

**Comment by vsergeev** [comment]
Did you provide a location in the settings? If not, is it possible you denied the geolocation prompt? Either way, let me know what it says in the console to help pinpoint the problem.

**Comment by mhkeller** [comment]
Ah it was the location settings. All working now thanks!

**Comment by nfriedly** [comment]
I just ran into this also - that error message is really confusing. The issue was location, not the selected API, and the error doesn't say anything about that.

In my case, it had worked fine for months, but location permission apparently got reset with a browser update, and the app didn't even prompt for it - it just gave me the example provider warning and bogus data.

**Comment by vsergeev** [comment]
> I just ran into this also - that error message is really confusing. The issue was location, not the selected API, and the error doesn't say anything about that.
> 
> In my case, it had worked fine for months, but location permission apparently got reset with a browser update, and the site didn't even prompt for it - it just gave me the example provider warning and bogus data.

I improved the warning in v1.6.0 for missing location, hopefully that helps future users.
